const STORY_ARCHIVE = 'STORY_ARCHIVE' ;
const STORIES_FETCH = 'STORIES_FETCH' ;
const STORIES_ADD = 'STORIES_ADD' ;
const STORIES_FETCH_ERROR ='STORIES_FETCH_ERROR';

export { STORIES_ADD, STORY_ARCHIVE, STORIES_FETCH,STORIES_FETCH_ERROR }


